name: openweathermap_api_flutter
description: "OpenWeatherMap API Flutter."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Redux is a predictable state container for Dart and Flutter apps
  redux: ^5.0.0
  # A set of utility Widgets that Provide and Connect to a Redux Store
  flutter_redux: ^0.10.0
  # A Redux.dart Middleware that allows you to dispatch functions that perform async work as actions.
  redux_thunk: ^0.4.0
  # Smart project structure with dependency injection and route management
  flutter_modular: 5.0.3
  # A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.4.1
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.1
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1
  # This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
  geolocator: ^11.0.0
  # A highly customizable typeahead (autocomplete) text input field for Flutter
  flutter_typeahead: ^5.2.0
  # An implementation of the internationalization, localization, and formatting conventions for the Dart language.
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0

  # Remote DevTools for Redux.dart. This package connects a Dart Redux store to the Remote Devtools Server, allowing the developer to inspect changes to the Redux Store during runtime.
  redux_remote_devtools: ^3.0.0
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.8.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.7
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.8

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/weather_icons/
